import type { DataSourceType, VerificationStatus } from "./provenance";
import type { FieldStatus } from "./field-status";

// DOMAIN.md §8a — a manufacturer-created stand-in for a supplier
// product that isn't (yet) registered by a real supplier in Greendeal
// (AGENTS.md §10a scenarios 2 & 4). Owned by the Manufacturer, not the
// Supplier — this is deliberately NOT a SupplierProduct (see
// lib/types/product.ts): it has no ProductVersion, no Evidence, no
// publish/draft lifecycle.
//
// Stage 7.11 — `hasSupplier` is the real discriminator between the two
// Add Component paths this type serves (see
// components/packaging/add-component-flow.tsx), replacing Stage 7.3's
// conflated MANUFACTURER_PROVIDED-vs-IMPORTED "lighter-weight form"
// framing:
// - hasSupplier: true — "Add External Supplier Product". A real
//   supplier exists (name + email); the manufacturer knows partial data
//   and can ask the supplier to complete the rest via the Supplier
//   Response Link (Stage 7.10). verificationStatus can eventually
//   become SUPPLIER_APPROVED once that response is completed.
// - hasSupplier: false — "Use Existing Manufacturer-Provided Data". No
//   supplier entity exists at all — the manufacturer already has
//   complete data from their own records (email thread, PDF,
//   spreadsheet, ERP) and is the permanent, sole source. No
//   supplierCompanyName/contact/email/country is ever collected for
//   this path (there's nothing to collect), there is no one to invite
//   or request more from, and verificationStatus stays UNVERIFIED
//   forever — that is the permanent, correct state, not a bug or a
//   step on the way to something else.
export type ExternalSupplierProduct = {
  id: string;
  createdByManufacturerId: string;
  hasSupplier: boolean;
  supplierCompanyName?: string; // only ever set when hasSupplier is true
  supplierContactName?: string;
  supplierEmail?: string; // required when hasSupplier is true (needed for the Supplier Response Link)
  supplierCountry?: string;
  productName: string;
  supplierSku?: string;
  gtin?: string;
  knownMaterialFamily?: string;
  knownMaterialComposition?: string;
  knownWeightGrams?: number;
  // Always MANUFACTURER_PROVIDED at creation, for BOTH paths — it's the
  // manufacturer who created this record either way. Only a hasSupplier:
  // true record can later become EXTERNAL_REQUEST_RESPONSE (Stage 7.10,
  // once the actual supplier completes a response); a hasSupplier:false
  // record's sourceType never changes — there's no supplier response to
  // receive.
  sourceType: DataSourceType;
  // UNVERIFIED at creation, for both paths. Only a hasSupplier:true
  // record can later become SUPPLIER_APPROVED (Stage 7.10). A
  // hasSupplier:false record's verificationStatus stays UNVERIFIED
  // permanently — there is no supplier who could ever approve it, no
  // matter how complete the data is (see readiness's UNVERIFIED_COMPLETE
  // state for how completeness is still tracked honestly despite this).
  verificationStatus: VerificationStatus;
  claimedBySupplierId?: string; // only ever applies when hasSupplier was true (not built yet — AGENTS.md §11)

  // Stage 7.10 — Supplier Response Link (AGENTS.md's "Supplier Response
  // Link" section). Only ever meaningful when hasSupplier is true —
  // there is no one to send this to, and no response page will ever be
  // reachable for it, when hasSupplier is false.
  responseToken?: string; // generated by requestInformationFromSupplier; identifies /supplier-response/{token}
  responseStatus: "NOT_SENT" | "SENT" | "COMPLETED";

  // Compliance data fields. Mirror lib/readiness.ts's REQUIRED_PPWR_FIELDS
  // (Circularity + Chemical Safety) plus a few additional Physical
  // fields, so this record can genuinely move readiness forward
  // (computeExternalComponentReadiness) once real values are present —
  // either via a completed Supplier Response (hasSupplier: true, Stage
  // 7.10) or directly at creation via the full "Use Existing
  // Manufacturer-Provided Data" form (hasSupplier: false, Stage 7.11).
  // Still NOT full ProductVersion parity (no versioning) — this always
  // stays an ExternalSupplierProduct, it never converts into a real
  // SupplierProduct/ProductVersion (AGENTS.md §11 remains out of scope).
  knownDimensions?: string;
  knownThicknessMm?: number;
  knownPackagingFunction?: string;
  totalRecycledContentPercent?: number;
  pcrYieldPercent?: number;
  preConsumerYieldPercent?: number;
  dfrGrade?: string;
  heavyMetalPpm?: number;
  pfasStatus?: FieldStatus;
  reachSvhcStatus?: FieldStatus;
  scipCode?: string;
  rohsStatus?: FieldStatus;
  // Stage 7.11 — Specialized Domain Metrics (DOMAIN.md §2 Section 5),
  // collected by the full "Use Existing Manufacturer-Provided Data"
  // form. Not part of REQUIRED_PPWR_FIELDS (same scoping rationale as
  // the native ProductVersion's own specializedDomain data — neither is
  // read by lib/assessment-findings.ts today), so these never affect
  // readiness/assessment computation, only informational display.
  fcmStatus?: FieldStatus;
  omlTestScore?: string;
  sterilizationProfile?: string;
  // Mocked evidence per the Stage 1b convention (lib/wizard/types.ts's
  // EvidenceDraft) — filenames only, nothing actually uploaded/parsed.
  // Populated either via a completed Supplier Response (hasSupplier:
  // true) or directly at creation (hasSupplier: false, Stage 7.11's own
  // evidence upload section).
  evidenceDocumentNames?: string[];
};
