import type { DataSourceType, VerificationStatus } from "./provenance";
import type { FieldStatus } from "./field-status";

// DOMAIN.md §8a — a manufacturer-created stand-in for a supplier
// product that isn't (yet) registered by a real supplier in Greendeal
// (AGENTS.md §10a scenarios 2 & 4). Owned by the Manufacturer, not the
// Supplier — this is deliberately NOT a SupplierProduct (see
// lib/types/product.ts): it has no ProductVersion, no Evidence, no
// publish/draft lifecycle, because no supplier is maintaining it yet.
//
// sourceType/verificationStatus distinguish the two scenarios this
// stage builds (see lib/services/mockExternalSupplierService.ts and
// components/packaging/add-component-flow.tsx for exactly which path
// sets which value):
// - MANUFACTURER_PROVIDED — the manufacturer is standing this in as a
//   real supplier they intend to onboard (full contact details
//   captured so "Invite Supplier" is meaningful).
// - IMPORTED — the manufacturer already has this compliance data on
//   hand from some other existing source (email/PDF/ERP/spreadsheet)
//   and is just entering it directly; no onboarding is implied.
// Both start UNVERIFIED — nothing in this stage upgrades that; a real
// Supplier "claiming" this record (Stage 7.4/7.5+) is what would.
export type ExternalSupplierProduct = {
  id: string;
  createdByManufacturerId: string;
  supplierCompanyName: string;
  supplierContactName?: string;
  supplierEmail?: string;
  supplierCountry?: string;
  productName: string;
  supplierSku?: string;
  gtin?: string;
  knownMaterialFamily?: string;
  knownMaterialComposition?: string;
  knownWeightGrams?: number;
  sourceType: DataSourceType; // typically MANUFACTURER_PROVIDED or IMPORTED, or EXTERNAL_REQUEST_RESPONSE once a supplier response is completed (see below)
  verificationStatus: VerificationStatus; // typically UNVERIFIED, or SUPPLIER_APPROVED once a supplier response is completed
  claimedBySupplierId?: string; // set if a real Supplier later "claims" this (not built yet — full onboarding remains out of scope, see AGENTS.md §11)

  // Stage 7.10 — Supplier Response Link (AGENTS.md's "Supplier Response
  // Link" section). A manufacturer can ask the ACTUAL supplier behind
  // this record to review/correct/complete it via a public, token-based
  // link — distinct from the Public Request Link (§8a), which is a
  // requester asking a supplier for data, not a manufacturer asking a
  // specific already-identified supplier to fill in a specific record.
  responseToken?: string; // generated by requestInformationFromSupplier; identifies /supplier-response/{token}
  responseStatus: "NOT_SENT" | "SENT" | "COMPLETED";

  // The fields below are populated by submitSupplierResponse once the
  // supplier actually completes the response form. They deliberately
  // mirror exactly the fields lib/readiness.ts's REQUIRED_PPWR_FIELDS
  // gates a PPWR assessment on (Circularity + Chemical Safety) plus a
  // couple of additional Physical fields the response form also
  // collects — so a completed response can genuinely move readiness
  // forward (see computeExternalComponentReadiness) instead of always
  // reporting UNVERIFIED. This is still NOT full ProductVersion parity
  // (no Specialized Domain/FCM fields, no versioning, no Identification
  // section beyond what's already above) — a completed response stays
  // an ExternalSupplierProduct, it never converts into a real
  // SupplierProduct/ProductVersion (AGENTS.md §11 remains out of scope).
  knownDimensions?: string;
  knownThicknessMm?: number;
  knownPackagingFunction?: string;
  totalRecycledContentPercent?: number;
  pcrYieldPercent?: number;
  preConsumerYieldPercent?: number;
  dfrGrade?: string;
  heavyMetalPpm?: number;
  pfasStatus?: FieldStatus;
  reachSvhcStatus?: FieldStatus;
  scipCode?: string;
  rohsStatus?: FieldStatus;
  // Mocked evidence per the Stage 1b convention (lib/wizard/types.ts's
  // EvidenceDraft) — filenames only, nothing actually uploaded/parsed.
  responseEvidenceDocumentNames?: string[];
};
